---

nginx_max_clients: 512

nginx_http_params:
  sendfile: "on"
  tcp_nopush: "on"
  tcp_nodelay: "on"
  keepalive_timeout: "65"

nginx_log_dir: "/var/log/nginx"
nginx_access_log_name: "access.log"
nginx_error_log_name: "error.log"
nginx_separate_logs_per_site: False

nginx_sites:
 - server:
    file_name: janus-demos
    listen: 80
    server_name: localhost
    root: "/opt/janus/share/janus/demos"
    location1: {name: /, try_files: "$uri $uri/ /index.html"}
 - server:
    file_name: janus-ssl-demos
    listen: "443 default ssl"
    ssl: "on"
    root: "/opt/janus/share/janus/demos"
    ssl_certificate: "/home/vagrant/keys/server.crt"
    ssl_certificate_key: "/home/vagrant/keys/server.key"
    server_name: "localhost"
    location1: {name: /, try_files: "$uri $uri/ /index.html"}
