---
# tasks file for provisioning/roles/base

- name: clone signalinggateway repo on home directory
  git: repo=https://github.com/eastandwest/signalinggateway.git force=yes dest=/home/{{remote_user}}/signalinggateway

- name: install depedency libraries
  command: npm install --production
  args:
    chdir: /home/{{remote_user}}/signalinggateway

- name: change owner
  command: chown -R {{remote_user}}.{{remote_user}} /home/{{remote_user}}/signalinggateway