---
# tasks file for provisioning/roles/base

- name: clone signalinggateway repo on home directory
  git: repo=https://github.com/eastandwest/signalinggateway.git version=v0.4.3 dest=/home/ubuntu/signalinggateway

- name: install depedency libraries
  command: npm install --production
  args:
    chdir: /home/ubuntu/signalinggateway

- name: change owner
  command: chown -R ubuntu.ubuntu /home/ubuntu/signalinggateway
