---
# tasks file for provisioning/roles/gstreamer
- name: Install gstreamer1.0
  apt:
    pkg: "{{item}}"
    state: installed
  with_items:
  - libgstreamer1.0-0
  - libgstreamer1.0-dev
  - gstreamer1.0-nice
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-good
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-doc
  - gstreamer1.0-tools
