---
- hosts: default
  remote_user: vagrant
  tasks:
  - name : Get aptitude for upgrade
    apt : pkg=aptitude state=present

  - name : install dependency libraries
    become : yes
    become_method : sudo
    apt : pkg={{item}} state=present update_cache=yes
    with_items :
      - libmicrohttpd-dev
      - libjansson-dev
      - libnice-dev
      - libssl-dev
      - libsrtp-dev
      - libsofia-sip-ua-dev
      - libglib2.0-dev
      - libopus-dev
      - libogg-dev
      - libini-config-dev
      - libcollection-dev
      - pkg-config
      - gengetopt
      - libtool
      - automake
      - cmake
  - name : install janus
    script : ./files/janus.sh
