---
- hosts: default
  remote_user: vagrant
  tasks:
  - name: clean up for debug
    command: bash -c "rm -rf .nvm"

  - name: install nvm
    command: bash -c "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash"

  - name: install node
    command: bash --rcfile .bashrc -ci "nvm install v5.0;echo 'nvm use 5.0' >> .bashrc"
